### ISSUE TITLE
Write GitScrapper Core

### ISSUE THREAD

**Issue by FarazzShaikh** [HWTechClub/gitscraper#1]
# Core

Write a functions that scrapes a GitHub (specified in a config file) and gives json object with all relevant data.

- [x]  d56e7ac Read config file (gitscrapper.json)
- [x]  #4 Find and write selectors for profile elements
- [x] 9805ea5 Selectors must be defined in and read from gitscrapper.json
- [x] #4 Use Cheerio to get the data
- [x] #4 Format data as a json object
- [ ] #8 URL Routing
- [ ] Refactor URL Routing to work inside a server
- [ ] Error handling
- [x] #9 Write tests 

All of this can be done without touching Firebase.

**Comment by Gaurav-Gosain** [comment]
I would like to take this up!

**Comment by FarazzShaikh** [comment]
@Gaurav-Gosain `->` #4
